server:
  port: 8081
spring:
  application:
    name: escola
  datasource:
    url: jdbc:mysql://localhost:3306/escola
    username: root
    password: app_employees
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none   # OPTIONS: none, validate, update, create-drop
    defer-datasource-initialization: true
  sql:
    init.mode: always
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  h2:
    console.enabled: true  # Enables H2 browser page on: /h2-console

#server:
#  port: 8081
#spring:
#  application:
#    name: escola
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/escola
#    username: root
#    password: app_employees
#  jpa:
#    hibernate.ddl-auto: none
#    generate-ddl: false
#    show-sql: false